[phases.setup]
nixPkgs = ['nodejs_20', 'python3', 'gcc', 'gnumake']

[phases.install]
cmds = ['cd website && npm install']

[phases.build]
cmds = ['cd website && npm run build']

[start]
cmd = 'cd website && npm start'