[[services]]
name = "kob-gallery-web"
source = "./website"

[services.kob-gallery-web.build]
builder = "NIXPACKS"

[services.kob-gallery-web.deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10